name: sync actions forks
permissions:
  contents: write
on:
  push:
    branches: sync-forks
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch: {}
jobs:
  # prepare:
  #   runs-on: ubuntu-latest
  #   if: ${{ startsWith(github.repository, 'mountainmoss/') == false }}
  #   steps:
  #   - name: require GeoNet org
  #     run: |
  #       exit 1
  sync-forks:
    env:
      FORKS:
    runs-on: ubuntu-latest
    steps:
      # - name: configure system
      #   run: |
      #     gh auth login --with-token < <(echo ${{ secrets.MOUNTAINMOSSBOT_TOKEN }})
      #     gh auth status
      - name: sync changes
        id: sync-changes
        env:
          GH_TOKEN: ${{ secrets.MOUNTAINMOSSBOT_TOKEN }}
        run: |
          gh auth login --with-token < <(echo ${{ secrets.MOUNTAINMOSSBOT_TOKEN }})
          xargs --help
          #echo -n "mountainmoss/chainguard-dev-actions" "mountainmoss/setup-ko" "mountainmoss/setup-crane" "mountainmoss/golangci-lint-action" "mountainmoss/conform-actions" "mountainmoss/chainguard-images-actions" "mountainmoss/terraform-linters-setup-tflint" | xargs -I -d ' ' gh api --method POST -f -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/{}/merge-upstream"
        shell: bash
