name: sync actions forks
permissions:
  contents: write
on:
  push:
    branches: sync-forks
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch: {}

jobs:
  # prepare:
  #   runs-on: ubuntu-latest
  #   if: ${{ startsWith(github.repository, 'mountainmoss/') == false }}
  #   steps:
  #   - name: require GeoNet org
  #     run: |
  #       exit 1
  sync-forks:
    env:
      FORKS: "mountainmoss/chainguard-dev-actions,mountainmoss/setup-ko,mountainmoss/setup-crane,mountainmoss/golangci-lint-action,mountainmoss/conform-actions,mountainmoss/chainguard-images-actions,mountainmoss/terraform-linters-setup-tflint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sync changes
        id: sync-changes
        env:
          GH_TOKEN: ${{ secrets.MOUNTAINMOSSBOT_TOKEN }}
        run: |
          echo -n "$FORKS" | xargs -I{} -d ',' gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/{} --template '{{.full_name}} {{.default_branch}}{{"\n"}}' | xargs -I{} hack/update-forks.sh {}
        shell: bash
