name: sync actions forks
#REQUIRES PAT WITH REPO(READ,WRITE) ORG(READ) WORKFLOWS(WRITE)

on:
  push:
    branches: sync-forks
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch: {}

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.repository, 'mountainmoss/') == false }}
    steps:
    - name: require GeoNet org
      run: |
        exit 1
  sync-forks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sync changes
        id: sync-changes
        env:
          GH_TOKEN: ${{ secrets.GH_CI_USER_TOKEN }}
        run: |
          gh repo list mountainmoss --no-archived --fork --json nameWithOwner --jq '.[].nameWithOwner' \
          | xargs -I{} gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/{} --template '{{.full_name}},{{.default_branch}}{{"\n"}}' \
          | xargs -I{} hack/update-forks.sh {}
        shell: bash
